name = "ids"
version = "0.11.0"
licences = ["Apache-2.0"]
description = "✨ Unique IDs for Gleam"
repository = { type = "github", user = "rvcas", repo = "ids" }
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_otp = "~> 0.8"
gleam_erlang = "~> 0.23"

[dev-dependencies]
gleeunit = "~> 1.0"
